### ISSUE TITLE
Flow file corrupted: mitmproxy 9.0.1 cannot read files with flow format version 20, please update mitmproxy.

### ISSUE THREAD

**Issue by flexaddicted** [alufers/mitmproxy2swagger#110]
Hello,

using the latest versions of mitmproxy and mitmproxy2swagger I'm experience the following error.

> Flow file corrupted: mitmproxy 9.0.1 cannot read files with flow format version 20, please update mitmproxy.
Done!

The flow file contains just a request (with associated response).

This is the command I'm executing:

`mitmproxy2swagger -i flows -o out -p https://base_url/`

Any hint on how to fix it?

Thanks,
Lorenzo

**Comment by alufers** [comment]
Updated
