### ISSUE TITLE
HAR from Firefox not loaded

### ISSUE THREAD

**Issue by stoeps13** [alufers/mitmproxy2swagger#12]
When I try to process a HAR from Firefox I get "Flow file corrupted: Invalid data format."
``` 
.local/bin/mitmproxy2swagger -i www.google.com_Archive\ \[22-06-06\ 18-09-31\].har -o temp -p https://www.google.com
No existing swagger file found. Creating new one.
Flow file corrupted: Invalid data format.
Done!
``` 
[www.google.com_Archive [22-06-06 18-09-31].zip](https://github.com/alufers/mitmproxy2swagger/files/8845833/www.google.com_Archive.22-06-06.18-09-31.zip)

I did an example with Google search. See attached file.

**Comment by alufers** [comment]
Hi!

#13 fixed this problem. You can now use `--format har` to force decoding as HAR.
