### ISSUE TITLE
Stuck at No existing swagger file found. Creating new one.

### ISSUE THREAD

**Issue by aannjjiill** [alufers/mitmproxy2swagger#16]
![image](https://user-images.githubusercontent.com/39268311/191399113-3ff6e178-ebc4-49d1-9d20-78a61d13ab3f.png)

I even used sudo but still nothing. and I am using python3.10. Help!!

**Comment by aannjjiill** [comment]
Turns out I did not specify the full URL for the site I hosted locally. It works now!

**Comment by ivartheterrible** [comment]
how did you fix this? having the same problem
