### ISSUE TITLE
Error thrown at generating spec

### ISSUE THREAD

**Issue by alejandro501** [alufers/mitmproxy2swagger#18]
When I'm trying to run the command for generating spec.yml I get an exception 

**File "/usr/local/bin/mitmproxy2swagger", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/mitmproxy2swagger/mitmproxy2swagger.py", line 127, in main
    path = strip_query_string(url).removeprefix(args.api_prefix)
AttributeError: 'str' object has no attribute 'removeprefix'**

 I've tried it with multiple targets and I certainly do have the endpoints exported that could be processed so my guess is there's something wrong with **mitmproxy2swagger** itself but I can't seem to find out what it is. Anyone has had similar problems?

**Comment by alufers** [comment]
Hi!
Your Python installation is too old, please use at least Python 3.9.

**Comment by alejandro501** [comment]
Thank so much for the quick answer! In that case, could you help me how to run it on 3.9? I'm using Ubuntu and pip3 is defaulting on 3.8, I spent an hour on it but can't seem to make it use the newer version so I'm still stuck. :( Thanks very much!
