### ISSUE TITLE
Error with good mitmproxy version : "Flow file corrupted: mitmproxy 8.1.1 cannot read files with flow format version 18, please update mitmproxy" 

### ISSUE THREAD

**Issue by PaulAZC** [alufers/mitmproxy2swagger#21]
Hello,

I have a problem to install mitmproxy2swagger on my computer (I tried for 1 and half hour). It gives me the following error : "Flow file corrupted: mitmproxy 8.1.1 cannot read files with flow format version 18, please update mitmproxy".

Btw, it don't recognize my command when I try with sudo and my mitmproxy version is : 
Mitmproxy: 9.0.1

Thanks

**Comment by neoyagami** [comment]
I have the exact same issue :\

**Comment by alufers** [comment]
Hey!

Your mitmproxy was too new for mitmproxy2swagger. I have updated it's dependencies in 1.72. It should work now. 

If it doesn't please open another issue.

Thank you.

**Comment by BreakShoot** [comment]
So what versions of mitmproxy are compatible with the latest release 0.7.2???
