### ISSUE TITLE
Allow later json-stream

### ISSUE THREAD

**Issue by fabaff** [alufers/mitmproxy2swagger#27]
[`json-stream`](https://github.com/daggaz/json-stream) was updated a while ago. In the meantime they are at 2.2.0.

Would it be possible to support later releases of `json-stream`? Thanks

**Comment by alufers** [comment]
Yup will update

I should setu one of these bots which auto bumps dependencies :D

**Comment by fabaff** [comment]
Thank you.

**Comment by alufers** [comment]
Done, fixed in 0.8.2
