### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by kpcyrd** [alufers/mitmproxy2swagger#4]
hi!

I'm interested in packaging mitmproxy2swagger for Arch Linux, any chance you could create a 0.1.0 tag+release on github? :) Just a tag is sufficient, but releases would also show up in my github notifications inbox.

Thanks!

**Comment by alufers** [comment]
Hi! No problem, i will do so on the next release today.

**Comment by alufers** [comment]
Hi! I have created a release: https://github.com/alufers/mitmproxy2swagger/releases/tag/0.5.0

**Comment by kpcyrd** [comment]
Thanks!

I have a package ready that currently fails to start due to a missing dependency:

```
% mitmproxy2swagger 
Traceback (most recent call last):
  File "/usr/bin/mitmproxy2swagger", line 5, in <module>
    from mitmproxy2swagger.mitmproxy2swagger import main
  File "/usr/lib/python3.10/site-packages/mitmproxy2swagger/mitmproxy2swagger.py", line 16, in <module>
    import swagger_util
ModuleNotFoundError: No module named 'swagger_util'
```

I checked `pyproject.toml` and `poetry.lock` but couldn't figure it out which pypi package is needed, can you give me a hint? :)

**Comment by alufers** [comment]
Oh sorry, I broke the imports myself (I really hate python module resolution), here is a fixed release:

https://github.com/alufers/mitmproxy2swagger/releases/tag/0.5.1
